### ISSUE TITLE
Nerf and bantha wool missing proper stuffpower property

### ISSUE THREAD

**Issue by x7GoSu** [emipa606/StarWarsAnimalCollection#1]
<statFactors>
        <StuffPower_Armor_Sharp>1.1</ArmorRating_Sharp>
        <StuffPower_Armor_Heat>2.2</ArmorRating_Heat>
        <StuffPower_Insulation_Cold>3.0</Insulation_Cold>
        <StuffPower_Insulation_Heat>3.0</Insulation_Heat>
      </statFactors>

**Comment by emipa606** [comment]
Added in a16751e
Made it slightly better than megasloth
